spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
